//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RoboMX_DE.rc
//
#define IDR_MANIFEST                    1
#define IDB_ABOUTBG                     100
#define IDB_BG                          101
#define IDB_BITMAP1                     102
#define IDB_BITMAP2                     103
#define IDB_BITMAP3                     104
#define IDB_BITMAP4                     105
#define IDB_CHANNELLIST                 106
#define IDB_HDRDOWN                     107
#define IDB_HDRUP                       108
#define IDB_MENU_BUTTON                 109
#define IDB_PREVIEW                     111
#define IDB_SMILEYS                     113
#define IDB_TOOLBAR256                  114
#define IDB_TOOLBAR256_DEACT            115
#define IDB_VOICE_MALE                  117
#define IDD_ABOUTBOX                    118
#define IDD_ADD_CACHE                   119
#define IDD_APP_EXIT                    120
#define IDD_AUTOJOIN_MANAGER            121
#define IDD_BROWSE_VIEW                 122
#define IDD_CFG_GENERAL                 123
#define IDD_CFG_WELCOME                 124
#define IDD_CHANNELLIST                 125
#define IDD_COLORS                      126
#define IDD_CFG_COLORS                  126
#define IDD_CONFIRM_EXIT                127
#define IDR_MAINFRAME                   128
#define IDD_EDIT_ROOM_FILTER            129
#define IDD_EXTENSIONS                  130
#define IDD_CFG_EXTENSIONS              130
#define IDD_FUN                         131
#define IDD_CFG_FUN                     131
#define IDD_IGNORED_USERS               132
#define IDD_INPUT_REQUEST               133
#define IDD_LINK_WARNING                134
#define IDD_LOGVIEW                     135
#define IDD_MESSAGE_VIEW                136
#define IDD_MESSAGES                    137
#define IDD_CFG_MESSAGES                137
#define IDD_ROBOMX_FORM                 138
#define IDD_CHAT_FORM                   138
#define IDD_PAGERCFG                    139
#define IDD_RENAME                      140
#define IDD_SETTINGS                    141
#define IDD_SOUND                       143
#define IDD_CFG_SYSSOUNDS               143
#define IDD_TRUSTED_USERS               144
#define IDD_WPN_SETUP                   147
#define IDD_CFG_WPN                     147
#define IDI_ANI                         148
#define IDI_EXCLAMATION_ICON            149
#define IDI_ICON1                       150
#define IDI_LOGFILE                     151
#define IDI_ROOM                        152
#define IDI_SECURITY                    153
#define IDI_USERSETUP                   154
#define IDM_AWAY                        155
#define IDR_BACK                        157
#define IDR_BROWSE                      158
#define IDR_BROWSEVIEW_TMPL             159
#define IDR_CHANNEL                     160
#define IDR_CHAT                        161
#define IDR_DOCMENU                     162
#define IDR_FULLSCREEN                  163
#define IDR_LIST                        164
#define IDR_LISTRMENU                   165
#define IDD_CONNECT                     166
#define IDR_MAINFRAME1                  167
#define IDR_MESSAGEVIEW_TMPL            168
#define IDR_ROBOMXTYPE                  169
#define IDR_PM                          170
#define IDR_PRIVATECHAT_TMPL            171
#define IDR_SERVER                      172
#define IDR_SETTINGS                    173
#define IDR_START_NODESERVER            174
#define IDR_SYSTRAY                     175
#define IDR_URL                         176
#define IDR_USER                        177
#define IDS_ADD                         178
#define IDS_AUTHOR                      179
#define IDS_AUTOJOIN_ADD                180
#define IDS_AUTOJOIN_REMOVE             181
#define IDS_AVERAGE_LAG                 182
#define IDS_AVERAGE_LAG_CHAT            183
#define IDS_AWAY_BACK                   184
#define IDS_AWAY_CONTROL                185
#define IDS_AWAY_PM                     186
#define IDS_AWAY_SILENTBACK             187
#define IDS_AWAYCTRL                    188
#define IDS_BANLISTING                  189
#define IDS_BANLISTINGEND               190
#define IDS_BANLISTINGSTART             191
#define IDS_BATH                        192
#define IDS_BEER                        193
#define IDS_BITMAP_FILTER               194
#define IDS_BROWSE_CMPLT                195
#define IDS_BROWSE_HEAD                 196
#define IDS_BROWSE_TITLE                197
#define IDS_CFG_COLORS                  198
#define IDS_CFG_EXT                     199
#define IDS_CFG_FUN                     200
#define IDS_CFG_GENERAL                 201
#define IDS_CFG_MSG                     202
#define IDS_CFG_SERVER                  203
#define IDS_CFG_SND                     204
#define IDS_CFG_WELCOME                 205
#define IDS_CHANNELLIST                 206
#define IDS_CHANNELSTATS1               207
#define IDS_CHANNELSTATS2               208
#define IDS_CHANNELSTATS3               209
#define IDS_CLIENTDISC                  210
#define IDS_COMMAND_EXECUTED            211
#define IDS_COMMAND_NOTUNDERSTOOD       212
#define IDS_CONNECTING                  213
#define IDS_CONNECTION_RETRY            214
#define IDS_CUSTOMIZE                   215
#define IDS_DEFAULT_KEYMSG              216
#define IDS_DEFAULT_MOTD                217
#define IDS_DEFAULT_TOPIC               218
#define IDS_DESC                        219
#define IDS_DISPLAY_USERLEVEL           220
#define IDS_EDIT_MENU                   221
#define IDS_EMO_ACT                     222
#define IDS_EMO_FILE                    223
#define IDS_ERROR_BG_LOAD               224
#define IDS_ERROR_CMDEMPTY              225
#define IDS_ERROR_COM                   226
#define IDS_ERROR_COMCTRL               227
#define IDS_ERROR_CONNECTFORCED         228
#define IDS_ERROR_CONNECTING            229
#define IDS_ERROR_FILE_GENERIC          230
#define IDS_ERROR_FIXME                 231
#define IDS_ERROR_INITSPEECH            232
#define IDS_ERROR_INVALID_PLUGIN        233
#define IDS_ERROR_INVALID_SOCKET        234
#define IDS_ERROR_KICKED                235
#define IDS_ERROR_LOGFILE_OPEN          236
#define IDS_ERROR_LOGFILE_WRITE         237
#define IDS_ERROR_LOGIN_KEY             238
#define IDS_ERROR_LOGIN_REJECTED        239
#define IDS_ERROR_LOGIN_UNKNOWN         240
#define IDS_ERROR_MISSING_INPUT         241
#define IDS_ERROR_MX353ONLY             242
#define IDS_ERROR_NAME_INVALID          243
#define IDS_ERROR_NAME_LONG             244
#define IDS_ERROR_NAME_SHORT            245
#define IDS_ERROR_NAMES_EMPTY           246
#define IDS_ERROR_NETWORK               247
#define IDS_ERROR_NO_CHATSERVER         248
#define IDS_ERROR_NO_SELECTION          249
#define IDS_ERROR_NODEREQUIRED          250
#define IDS_ERROR_NOTUNDERSTOOD         251
#define IDS_ERROR_NOTUNDERSTOOD_SEND    252
#define IDS_ERROR_OLE                   253
#define IDS_ERROR_PERMISSIONDENIED_SEND 254
#define IDS_ERROR_PLAYWAVE              255
#define IDS_ERROR_PLUGIN_INIT           256
#define IDS_ERROR_PLUGIN_LOAD           257
#define IDS_ERROR_PLUGIN_OLDAPI         258
#define IDS_ERROR_REDIRECT_ROOMNAMEINVALID 259
#define IDS_ERROR_REMOVE_PLUGIN         260
#define IDS_ERROR_RICHEDIT              261
#define IDS_ERROR_RICHEDIT_INIT         262
#define IDS_ERROR_ROOMNAME_EMPTY        263
#define IDS_ERROR_ROOMNAME_INVALID      264
#define IDS_ERROR_SELECT_PLUGIN         265
#define IDS_ERROR_SELECTEVENT           266
#define IDS_ERROR_SERVER_FILE           267
#define IDS_ERROR_SERVER_HANDSHAKE      268
#define IDS_ERROR_SERVER_HOST           269
#define IDS_ERROR_SERVER_KEYEXISTS      270
#define IDS_ERROR_SERVER_NOKEY          271
#define IDS_ERROR_SERVER_NOROOM         272
#define IDS_ERROR_SERVER_ONEROOMPERCONSOLE 273
#define IDS_ERROR_SERVER_SYNTAXERROR    274
#define IDS_ERROR_SERVER_WRONGKEY       275
#define IDS_ERROR_TIMEOUT               276
#define IDS_ERROR_UNKNOWN_ID            277
#define IDS_ERROR_WINSOCK               278
#define IDS_FILTEREDCHANNELS            279
#define IDS_FINISHED                    280
#define IDS_FIXME_NAME_ERROR            281
#define IDS_FIXME_UNKNOWN_COMMAND       282
#define IDS_FOOD                        283
#define IDS_FRESHAIR                    284
#define IDS_GIVE_VOICE                  285
#define IDS_GOOGLE_STR                  286
#define IDS_HANDSHAKE_START             287
#define IDS_HIDDENLISTING               288
#define IDS_HIDDENLISTINGEND            289
#define IDS_HIDDENLISTINGSTART          290
#define IDS_HILITE_LOADED               291
#define IDS_IGNORED                     292
#define IDS_IGNORED_MX353               293
#define IDS_IMAGE_FILTER                294
#define IDS_KICKBAN_5                   295
#define IDS_LIST                        296
#define IDS_LOG_START                   297
#define IDS_LOGIN_OK                    298
#define IDS_LURKMETER                   299
#define IDS_LURKMETER1                  300
#define IDS_LURKMETER2                  301
#define IDS_MODES                       302
#define IDS_NEWPM                       303
#define IDS_NOSUCHBAN                   304
#define IDS_NOTYOURBUISNESS             305
#define IDS_NOVOICE                     306
#define IDS_NUMCHANNELS                 307
#define IDS_PING                        308
#define IDS_PLUGIN                      309
#define IDS_PM_AWAY                     310
#define IDS_PM_NOTIME_WRITES            311
#define IDS_PM_NOTIME_YOUWRITE          312
#define IDS_PM_TIME_WRITES              313
#define IDS_PM_TIME_YOUWRITE            314
#define IDS_RECONNECTING                315
#define IDS_REDIRECT_USER               316
#define IDS_REDIRECTING                 317
#define IDS_REJOIN_ROOM                 318
#define IDS_REMOVE_PLUGIN               319
#define IDS_REMOVE_VOICE                320
#define IDS_ROBOMX_ROOMSERVER           321
#define IDS_ROOMLIST                    322
#define IDS_ROOMRENAME                  323
#define IDS_ROOMS_ETA                   324
#define IDS_RTF_BLOCK                   325
#define IDS_SEND_WHOIS                  326
#define IDS_SENDPM                      327
#define IDS_SERVER_CFG_LOADED           328
#define IDS_SERVER_CFG_SAVED            329
#define IDS_SERVER_EXILED               330
#define IDS_SERVER_FILTER               331
#define IDS_SERVER_HELP                 332
#define IDS_SERVER_KICKED               333
#define IDS_SERVER_MCMA                 334
#define IDS_SERVER_RCMS                 335
#define IDS_SERVER_ROOMRENAME           336
#define IDS_SERVER_SETMODE              337
#define IDS_SERVER_SUCCESS              338
#define IDS_SERVER_TERMINATED           339
#define IDS_SERVER_UNBAN                340
#define IDS_SERVER_WINMX353             341
#define IDS_SERVERNEW                   342
#define IDS_SETTINGS                    343
#define IDS_SLEEP                       344
#define IDS_SMOKE                       345
#define IDS_SOUND                       346
#define IDS_STORE                       347
#define IDS_TOOL_JOINVARIABLES          348
#define IDS_TOOL_MSGVARIABLES           349
#define IDS_TOOL_PARTVARIABLES          350
#define IDS_TOOL_SERVERVARIABLES        351
#define IDS_TOOL_WAVARIABLES            352
#define IDS_TOOL_WILDCARDS              353
#define IDS_TOPIC                       354
#define IDS_TOPIC2                      355
#define IDS_TRIGGER                     356
#define IDS_TV                          357
#define IDS_UNIGNORE                    358
#define IDS_UNIGNORE_MX353              359
#define IDS_UPDATE_AVAILABLE            360
#define IDS_USERLIST_NODE               361
#define IDS_USERLIST_SHORT              362
#define IDS_USERMNU                     363
#define IDS_USERMODES                   364
#define IDS_USERS                       365
#define IDS_WARN_USERNAMEHIJACK         366
#define IDS_WAVE_FILTER                 367
#define IDS_WHOIS_1                     368
#define IDS_WHOIS_2                     369
#define IDS_WHOIS_ERROR                 370
#define IDS_WINMX353_WRONGJOIN_WARNING  371
#define IDS_WORK                        372
#define IDS_WPN_CONNECTED               373
#define IDS_WPN_CONNECTING              374
#define IDS_WPN_DISCONNECTED            375
#define IDS_WPN_WARNING                 376
#define IDS_ZZZZZZZZ                    377
#define IDD_ADDFAV                      380
#define IDR_PMMENU                      383
#define IDB_FILETYPES                   384
#define IDI_PM_SYSTRAY                  385
#define IDI_ICON3                       386
#define IDI_PM2_SYSTRAY                 386
#define IDB_PREFERENCES                 387
#define IDD_CFG_EMOTICONS               388
#define IDD_CFG_FORMAT                  389
#define IDD_CFG_CHATSOUNDS              390
#define IDD_CFG_QUICKMSG                391
#define IDD_CFG_CHANNELBAR              393
#define IDD_CFG_USERTOOL                395
#define IDD_CFG_USERLIST                397
#define IDD_CFG_AWAY                    398
#define IDI_AWAY                        399
#define IDI_DISCONNECTED                400
#define IDI_CONNECTED                   401
#define IDI_FRIEND                      403
#define IDI_ICON2                       404
#define IDI_IGNORED                     404
#define IDD_CFG_PEERCACHE               405
#define IDC_ABOUTCTRL                   1000
#define IDC_ACCEPT_TRUSTED_ONLY         1001
#define IDC_ACTION_END                  1002
#define IDC_ACTION_FRONT                1003
#define IDC_ACTPEER                     1004
#define IDC_ACTTEXT                     1005
#define IDC_ADD                         1006
#define IDC_ADD_BOX                     1007
#define IDC_ADD_EMOTICON                1008
#define IDC_ADD_FEM                     1009
#define IDC_ADD_FEM_EDIT                1010
#define IDC_ADD_MALE                    1011
#define IDC_ADD_MALE_EDIT               1012
#define IDC_ADDCHANNEL                  1013
#define IDC_ADDCHANNEL2                 1014
#define IDC_ALLCHANNELS                 1015
#define IDC_ALLROOMS                    1016
#define IDC_ALWAYS_SHOW_WARNING         1017
#define IDC_ALWAYS_WARN                 1018
#define IDC_ANIMATION                   1019
#define IDC_APPLY                       1020
#define IDC_BACKG                       1021
#define IDC_BARTOP                      1022
#define IDC_BLOCKMCMA                   1023
#define IDC_BMP                         1024
#define IDC_BOLD                        1025
#define IDC_BROWSE_SOUND                1026
#define IDC_BTN_NAME_ADD                1027
#define IDC_BTN_SUFFIX_ADD              1028
#define IDC_BTN_VENDOR_ADD              1029
#define IDC_BUTTON1                     1030
#define IDC_CONNECTED_No                1030
#define IDC_CONNECTED_NO                1030
#define IDC_MXCONTROL                   1030
#define IDC_INSTALL                     1030
#define IDC_LICENSE                     1030
#define IDC_BTN_VENDOR_REM              1030
#define IDC_OPENFOLDER                  1030
#define IDC_BROWSE                      1030
#define IDC_CANCEL                      1031
#define IDC_TOPIC_NO                    1031
#define IDC_BTN_NAME_REM                1031
#define IDC_CANCELFILE                  1032
#define IDC_DISCONNECTED_NO             1032
#define IDC_BTN_SUFFIX_REM              1032
#define IDC_CAT                         1033
#define IDC_START_NO                    1033
#define IDC_CHANNELLIST                 1034
#define IDC_REDIRECT_NO                 1034
#define IDC_CHANNELNAME                 1035
#define IDC_MOTD_NO                     1035
#define IDC_CHANNELS                    1036
#define IDC_ERROR_NO                    1036
#define IDC_CHAT                        1037
#define IDC_PM_NO                       1037
#define IDC_CHAT_WND                    1038
#define IDC_CHECK1                      1039
#define IDC_AUTOJOIN                    1039
#define IDC_USEOLD                      1039
#define IDC_USE_BG_IMG                  1039
#define IDC_AWAY_IF_IDLE                1039
#define IDC_EXPERT                      1039
#define IDC_LOAD_LAST_LOG               1039
#define IDC_SEPERATOR                   1039
#define IDC_MCMARAW                     1039
#define IDC_CLEAR                       1040
#define IDC_CLEAR_REFRESH               1041
#define IDC_COLOR_ACTION                1042
#define IDC_COLOR_MESSAGE               1043
#define IDC_COLOR_NAME                  1044
#define IDC_COLORACTIONNAME             1045
#define IDC_COLORFOCUS                  1046
#define IDC_CONFIGURE                   1047
#define IDC_CONNECT                     1048
#define IDC_CONNECT_WPN                 1049
#define IDC_CONNECTED                   1050
#define IDC_CONVERT                     1051
#define IDC_DARK_LIGHT                  1052
#define IDC_DATES                       1053
#define IDC_DEFAULT_MALE                1054
#define IDC_DELETE                      1055
#define IDC_DELETE_EMOTICON             1056
#define IDC_DISCONNECTED                1057
#define IDC_DISPLAYPMTOOL               1058
#define IDC_DOCHI                       1059
#define IDC_EDIT                        1060
#define IDC_EDIT1                       1061
#define IDC_PRIVACY                     1061
#define IDC_LOGIN                       1061
#define IDC_CHANNEL                     1061
#define IDC_TOOLTIPHTML                 1061
#define IDC_LABEL                       1061
#define IDC_X_OFFSET                    1061
#define IDC_ADD_SERVER                  1061
#define IDC_EDIT_LIST                   1062
#define IDC_EDITHILITE                  1063
#define IDC_EMOTICONLIST                1064
#define IDC_EMOTICONS                   1065
#define IDC_ENABLE_CSFX                 1066
#define IDC_ENABLE_HISTORY              1067
#define IDC_ENABLE_SFX                  1068
#define IDC_ENC_ACTION_COLOR            1069
#define IDC_ENC_MSG_COLOR               1070
#define IDC_ENCODING                    1071
#define IDC_ERROR                       1072
#define IDC_EXIT                        1073
#define IDC_LINK                        1073
#define IDC_FEMALE_CHAR                 1074
#define IDC_FEMALE_VOICE                1075
#define IDC_FEMALES                     1076
#define IDC_FILE                        1077
#define IDC_FILE_FOLDER                 1078
#define IDC_FILE_LIST                   1079
#define IDC_FILES                       1080
#define IDC_FOCUSCLR                    1081
#define IDC_FONT                        1082
#define IDC_FONTSIZE                    1083
#define IDC_GET_NODE                    1084
#define IDC_GREETING                    1085
#define IDC_GRID_BG                     1086
#define IDC_GRID_TXT                    1087
#define IDC_HAND                        1088
#define IDC_HIDESYSTEM                  1089
#define IDC_HILITE                      1090
#define IDC_HILITE_TXT                  1091
#define IDC_HISTORDEPTH                 1092
#define IDC_IDLE_ANIM                   1093
#define IDC_IGNORED                     1094
#define IDC_IN                          1095
#define IDC_INPUT                       1096
#define IDC_ITALIC                      1097
#define IDC_JOIN                        1098
#define IDC_JOINRETRIES                 1099
#define IDC_KEEP_OPEN                   1100
#define IDC_LANG                        1101
#define IDC_LEAVE                       1102
#define IDC_LIGHT_DARK                  1103
#define IDC_LIMIT                       1104
#define IDC_LINE                        1105
#define IDC_LINES                       1106
#define IDC_LINESNUM                    1107
#define IDC_LISTCHANNEL                 1108
#define IDC_LOG                         1109
#define IDC_LOGDIR                      1110
#define IDC_MALE_CHAR                   1111
#define IDC_MALE_VOICE                  1112
#define IDC_MALES                       1113
#define IDC_MDIMAXI                     1114
#define IDC_MESSAGES                    1115
#define IDC_MINITRAY                    1116
#define IDC_MOTD                        1117
#define IDC_MOUTH_IMG                   1118
#define IDC_MSG_ADD                     1119
#define IDC_MSG_ADD_BTN                 1120
#define IDC_MSG_END                     1121
#define IDC_MSG_FRONT                   1122
#define IDC_MXCHATD                     1123
#define IDC_NAME                        1124
#define IDC_NAME_ADD                    1125
#define IDC_NAMES                       1126
#define IDC_NO_ANIM                     1127
#define IDC_NODEIP                      1128
#define IDC_NODENAME                    1129
#define IDC_NODENAME2                   1130
#define IDC_NOW_WATCHING                1131
#define IDC_NOWLISTENING                1132
#define IDC_OK                          1133
#define IDC_OPMSG                       1134
#define IDC_OPTTOP                      1135
#define IDC_OUT                         1136
#define IDC_OWN_NODE                    1137
#define IDC_PART                        1138
#define IDC_PATH                        1139
#define IDC_PENDING                     1140
#define IDC_PING                        1141
#define IDC_PLAY                        1142
#define IDC_PLAY_CONNECTED              1143
#define IDC_PLAY_DISCONNECTED           1144
#define IDC_PLAY_ERROR                  1145
#define IDC_PLAY_MOTD                   1146
#define IDC_PLAY_PM                     1147
#define IDC_PLAY_REDIRECTED             1148
#define IDC_PLAY_START                  1149
#define IDC_PLAY_TOPIC                  1150
#define IDC_PLUGINLIST                  1151
#define IDC_PM                          1152
#define IDC_PM_ALL                      1153
#define IDC_PORT                        1154
#define IDC_PREVIEW                     1155
#define IDC_PROGRESS1                   1156
#define IDC_PROGRESS                    1156
#define IDC_LETTERSLEFT                 1156
#define IDC_QUICKCMDS                   1157
#define IDC_QUICKDOWN                   1158
#define IDC_QUICKREM                    1159
#define IDC_QUICKUP                     1160
#define IDC_REACTION                    1161
#define IDC_REDIRECTED                  1162
#define IDC_REFRESH                     1163
#define IDC_RELOAD_ALL                  1164
#define IDC_REM_FEM                     1165
#define IDC_REM_MALE                    1166
#define IDC_REMEMBER_POS                1167
#define IDC_REMOVE                      1168
#define IDC_REMOVECHANNEL               1169
#define IDC_REMOVECHANNEL2              1170
#define IDC_RESCAN                      1171
#define IDC_RETRY_JOINS                 1172
#define IDC_RICHEDIT1                   1173
#define IDC_RICHEDIT2                   1174
#define IDC_ROOM                        1175
#define IDC_SCROLLER                    1176
#define IDC_SEARCH                      1177
#define IDC_SELECT_IMAGE                1178
#define IDC_SELECT_LOG_DIR              1179
#define IDC_SELECT_IMAGE2               1179
#define IDC_SELECT_AVATAR               1179
#define IDC_SELECTBMP                   1180
#define IDC_SELECT_IMAGE3               1180
#define IDC_SELECTION_NOSCROLL          1181
#define IDC_SERVER_INPUT                1182
#define IDS_DISPLAY_CHANNELSTAT         1182
#define IDC_SERVER_IP                   1183
#define IDC_SET_FOLDER                  1184
#define IDC_SETUP                       1185
#define IDC_SOUNDLIST                   1186
#define IDC_SPEAK_ONLY                  1187
#define IDC_SPLITTER_1                  1188
#define IDC_SPLITTER_2                  1189
#define IDC_STARTUP                     1190
#define IDC_STATIC_ACTION               1191
#define IDC_STATIC_ANI                  1192
#define IDC_STATIC_BG                   1193
#define IDC_STATIC_BGIMAGE              1194
#define IDC_STATIC_CHAT                 1195
#define IDC_STATIC_CHATSOUNDS           1196
#define IDC_STATIC_CLIENT               1197
#define IDC_STATIC_COLOR_ACTION_PREV    1198
#define IDC_STATIC_COLOR_ENC_MSG_PREV   1199
#define IDC_STATIC_COLOR_ENG_ACTION_PREV 1200
#define IDC_STATIC_COLOR_MSG_PREV       1201
#define IDC_STATIC_COLOR_NAME_PREV      1202
#define IDC_STATIC_CONNECT              1203
#define IDC_STATIC_CONNSTATUS           1204
#define IDC_STATIC_DISCONNECTED         1205
#define IDC_STATIC_DOCHI                1206
#define IDC_STATIC_EMOTICONS            1207
#define IDC_STATIC_END_ACTION           1208
#define IDC_STATIC_END_MSG              1209
#define IDC_STATIC_ERROR                1210
#define IDC_STATIC_FILES                1211
#define IDC_STATIC_FOCUS                1212
#define IDC_STATIC_FONT                 1213
#define IDC_STATIC_LINK                 1213
#define IDC_STATIC_FRONT_ACTION         1214
#define IDC_STATIC_FRONT_MSG            1215
#define IDC_STATIC_GREETING             1216
#define IDC_STATIC_GRID_BG              1217
#define IDC_STATIC_GRID_TXT             1218
#define IDC_STATIC_HILIGHT              1219
#define IDC_STATIC_HILITE               1220
#define IDC_STATIC_HILITE_TXT           1221
#define IDC_STATIC_IM                   1222
#define IDC_STATIC_IMAGEPATH            1223
#define IDC_STATIC_IR                   1224
#define IDC_STATIC_JOIN                 1225
#define IDC_STATIC_JOIN_VAR             1226
#define IDC_STATIC_JOINPART             1227
#define IDC_STATIC_LANG                 1228
#define IDC_STATIC_LINE                 1229
#define IDC_STATIC_MESSAGE              1230
#define IDC_STATIC_MESSAGES             1231
#define IDC_STATIC_MISCCOLOR            1232
#define IDC_STATIC_MOTD                 1233
#define IDC_STATIC_MSG                  1234
#define IDC_STATIC_MUSIC                1235
#define IDC_STATIC_NAME                 1236
#define IDC_STATIC_NAMES                1237
#define IDC_STATIC_NICKENC_MSG          1238
#define IDC_STATIC_NICKENC_MSG2         1239
#define IDC_STATIC_NICKNAME_ACTION      1240
#define IDC_STATIC_NICKNAME_MSG         1241
#define IDC_STATIC_NODEIP               1242
#define IDC_STATIC_NODEPORT             1243
#define IDC_STATIC_OPMSG                1244
#define IDC_STATIC_OPTIONS              1245
#define IDC_STATIC_OUT                  1246
#define IDC_STATIC_PART                 1247
#define IDC_STATIC_PART_VAR             1248
#define IDC_STATIC_PEERIP               1249
#define IDC_STATIC_PEERSERVER           1250
#define IDC_STATIC_PENDING              1251
#define IDC_STATIC_PLUGINS              1252
#define IDC_STATIC_PM                   1253
#define IDC_STATIC_PORT                 1254
#define IDC_STATIC_QUICK                1255
#define IDC_STATIC_RANDOMIZER           1256
#define IDC_STATIC_RECV                 1257
#define IDC_STATIC_REDIRECTED           1258
#define IDC_STATIC_RMX                  1259
#define IDC_STATIC_ROOM                 1260
#define IDC_STATIC_ROOMS                1261
#define IDC_STATIC_SEARCH               1262
#define IDC_STATIC_SFX                  1263
#define IDC_STATIC_SIZE                 1264
#define IDC_STATIC_STARTUP              1265
#define IDC_STATIC_STATUS               1266
#define IDC_STATIC_SUCCESS              1267
#define IDC_STATIC_SUFFIXES             1268
#define IDC_STATIC_SYSERROR             1269
#define IDC_STATIC_SYSOUT               1270
#define IDC_STATIC_SYSTEM               1271
#define IDC_STATIC_TIME                 1272
#define IDC_STATIC_TIMEFORMAT           1273
#define IDC_STATIC_TOPIC                1274
#define IDC_STATIC_TRANS                1275
#define IDC_STATIC_USERLIST             1276
#define IDC_STATIC_USERNAME             1277
#define IDC_STATIC_USERSETUP            1278
#define IDC_STATIC_VARS                 1279
#define IDC_STATIC_VENDORS              1280
#define IDC_STATIC_VIDEO                1281
#define IDC_STATIC_WINAMP               1282
#define IDC_STATUS                      1283
#define IDC_SUCCESS                     1284
#define IDC_SUFFIX_ADD                  1285
#define IDC_SUFFIXES                    1286
#define IDC_SYS                         1287
#define IDC_SYS_WND                     1288
#define IDC_SYSERROR                    1289
#define IDC_SYSOUT                      1290
#define IDC_TIME                        1291
#define IDC_TIMESTAMP                   1292
#define IDC_TOOL_353LOOPBACK            1293
#define IDC_TOPIC                       1294
#define IDC_TRIGGER                     1295
#define IDC_TRUSTED                     1296
#define IDC_UNDERLINE                   1297
#define IDC_UNINSTALL                   1298
#define IDC_UNLOAD_ALL                  1299
#define IDC_UPDATE                      1300
#define IDC_URL                         1301
#define IDC_USE_BGIMAGE                 1302
#define IDC_USE_WPNNAME                 1303
#define IDC_USENODE                     1304
#define IDC_USERHILITE                  1305
#define IDC_USERLIST                    1306
#define IDC_USERNAME                    1307
#define IDC_USERNAME_DISP               1308
#define IDC_USERS                       1309
#define IDC_VENDOR_ADD                  1310
#define IDC_VENDORS                     1311
#define IDC_WELCOMES                    1312
#define IDC_WINMX_LIKE                  1313
#define IDC_WPN_SETUP                   1314
#define IDC_NUSHI                       1315
#define IDC_STATIC1                     1316
#define IDC_STATIC2                     1317
#define IDC_STATIC3                     1318
#define IDC_STATIC4                     1319
#define IDC_STATIC_WA                   1320
#define IDC_LOGIN2                      1323
#define IDC_NETWORK                     1324
#define IDC_AUTOJOINS                   1326
#define IDC_TEXT_ACTION                 1327
#define IDC_COLOR                       1328
#define ID_SEND                         1329
#define ID_CLOSEPM                      1330
#define IDC_HOME                        1331
#define IDC_TOOLTIPTYPE                 1333
#define IDC_IMAGE                       1335
#define IDC_CHANNELIMAGES               1336
#define IDC_BG1                         1339
#define IDC_STATIC_BG1                  1340
#define IDC_BG2                         1341
#define IDC_STATIC_BG2                  1342
#define IDC_BG3                         1343
#define IDC_STATIC_BG3                  1344
#define IDC_BG_EFFECT                   1345
#define IDC_GRAN                        1346
#define IDC_TRANS                       1347
#define IDC_HELP_INET                   1348
#define IDC_VARS                        1349
#define IDC_USERIMAGES                  1351
#define IDC_EDITROOM                    1353
#define IDC_EDITWELCOME                 1354
#define IDC_STATIC_RMXVER               1354
#define IDC_DETAILED                    1355
#define IDC_COMPACT                     1356
#define IDC_BIGICON                     1357
#define IDC_NORMAL                      1360
#define IDC_ADMIN                       1361
#define IDC_VOICED                      1362
#define IDC_HOST                        1363
#define IDC_STATIC_NORMAL               1364
#define IDC_STATIC_VOICED               1365
#define IDC_STATIC_ADMIN                1366
#define IDC_STATIC_HOST                 1367
#define IDC_STATIC_PATH                 1369
#define IDC_SMALLICON                   1370
#define IDC_REASON                      1371
#define IDC_STATIC_PATH2                1371
#define IDC_STATIC_PATHAVATAR           1371
#define IDC_PREFIX                      1372
#define IDC_STATIC_PATH3                1372
#define IDC_SUFFIX                      1373
#define IDC_AWAY                        1374
#define IDC_AUTOREASON                  1375
#define IDC_AUTOPREFIX                  1376
#define IDC_AUTOSUFFIX                  1377
#define IDC_MINUTES                     1379
#define IDC_AUTOBACK                    1380
#define IDC_TILE                        1381
#define IDC_Y_OFFSET                    1382
#define IDC_BLUE                        1383
#define IDC_IMPORT                      1384
#define IDC_EXPORT                      1385
#define IDC_CHECK2                      1388
#define IDC_SHOWFILLSTATUS              1388
#define IDC_SERVERS                     1391
#define IDC_EDITPCS                     1392
#define IDC_TOOL_ROOM                   32383
#define IDS_CLEARINGLIST                32384
#define IDS_FILTERING                   32385
#define IDS_CLEARCACHE                  32386
#define IDS_LOADCACHE                   32387
#define IDS_CFG_CHATSOUND               32756
#define IDS_MISSING_INPUT               32757
#define IDS_CFG_QUICKMSG                32758
#define IDS_CFG_FORMAT                  32759
#define IDS_CFG_CHANNELBAR              32760
#define IDS_SPECIFYFIRST                32761
#define IDS_ERROR_CREATETOOL            32762
#define IDS_CFG_USERTOOL                32763
#define IDS_CFG_USERLIST                32764
#define IDS_PICINFO                     32765
#define IDS_AWAYREQUIRED                32766
#define IDS_CFG_AWAY                    32767
#define IDS_ENTERREASON                 32768
#define IDS_INI_FILTER                  32769
#define IDS_STATUSPREFIXLENGTHWARNING   32770
#define ID_ACTIONS_IGNOREUSER           32774
#define ID_ACTIONS_RELOADFILES          32775
#define ID_ACTIONS_SENDPRIVATEMESSAGE   32776
#define ID_ACTIONS_SETAWAYMESSAGE       32777
#define ID_ADVANCED_CLEARCACHEDROOMS    32779
#define ID_ADVANCED_MANUALLYADDROOMTOCACHE 32780
#define ID_ADVANCED_REMOVECACHEDFLAG    32781
#define ID_ADVANCED_REMOVEFROMCACHE     32782
#define ID_AWAYCONTROL_BATHROOM         32783
#define IDS_LOADFILES                   32783
#define ID_AWAYCONTROL_BEER             32784
#define IDS_CFG_EMO                     32784
#define ID_AWAYCONTROL_ENTERREASON      32785
#define IDS_CFG_WPN                     32785
#define ID_AWAYCONTROL_FOOD             32786
#define IDS_NEW_PM_TOOL                 32786
#define ID_AWAYCONTROL_FRESHAIR         32787
#define IDS_NEW_PM_TEXT                 32787
#define ID_AWAYCONTROL_NONEOFYOURBUISNESS 32788
#define IDS_STRING3                     32788
#define IDS_NEW_PM_TITLE                32788
#define ID_AWAYCONTROL_SLEEP            32789
#define ID_AWAYCONTROL_SMOKEBREAK       32790
#define ID_AWAYCONTROL_STORE            32791
#define ID_AWAYCONTROL_TV               32792
#define ID_AWAYCONTROL_WORK             32793
#define ID_AWAYCONTROL_ZZZZZZZZZZZZZZZZ 32794
#define ID_BACK_SETBACK                 32795
#define ID_BACK_SETSI8LENTBACK          32796
#define ID_BROWSE_COPYFILEINFORMATION   32797
#define ID_BROWSE_COPYFILENAME          32798
#define ID_BROWSE_COPYFILEPATH          32799
#define ID_CHANNEL_CHANNELLIST          32800
#define ID_CHANNELS_EDITFILTER          32801
#define ID_CHANNELS_FILTER              32802
#define ID_CHAT_CHANNELSTATISTICS       32803
#define ID_CHAT_TEXTTRICKS_3DBUTTONSACTION 32804
#define ID_CHAT_TEXTTRICKS_3DBUTTONSNORMAL 32805
#define ID_CHATROOM_ADDTOAUTOJOIN       32806
#define ID_CHATROOM_ASCIIARTDESIGN      32807
#define ID_CHATROOM_AWAYCONTROL_SETBACK 32808
#define ID_CHATROOM_AWAYCONTROL_SETSILENTBACK 32809
#define ID_CHATROOM_AWAYCONTROL_TEST    32810
#define ID_CHATROOM_CLEARSCREEN         32811
#define ID_CHATROOM_COPY                32812
#define ID_CHATROOM_COPYROOMNAME        32813
#define ID_CHATROOM_DISPLAYINCHANNEL_AVERAGELAG 32814
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMINFO 32815
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMUPTIME 32816
#define ID_CHATROOM_DISPLAYINCHANNEL_WINAMPSONG 32817
#define ID_CHATROOM_QUOTE               32818
#define ID_CHATROOM_REJOIN              32819
#define ID_CHATROOM_SEARCHONGOOGLE      32820
#define ID_CHATROOM_SELECTALL           32821
#define ID_CHATROOM_TEXTTRICKS_BOX      32822
#define ID_CHATROOM_TEXTTRICKS_BUBBLES  32823
#define ID_CHATROOM_TEXTTRICKS_HACKER   32824
#define ID_CHATROOM_VIEWCURRENTBANS     32825
#define ID_CHATROOM_VIEWTOPIC           32826
#define ID_CONFIGURECACHING_CACHEROOMLIST 32827
#define ID_CONTEXTMENU_CLOSE            32828
#define ID_COPY_ADDRESS                 32829
#define ID_CUSTOMIZE                    32830
#define ID_DISPLAYINCHANNEL_LURKMETER   32831
#define ID_DISPLAYINCHANNEL_PING        32832
#define ID_DOCMENU_ACTIVATE             32833
#define ID_DOCMENU_CLOSE                32834
#define ID_DOCMENU_MOVELEFT             32835
#define ID_DOCMENU_MOVERIGHT            32836
#define ID_EXIT                         32837
#define ID_HELP_VISITHOMEPAGE           32838
#define ID_LIST_ADDTOFAVORITES          32839
#define ID_LIST_ADVANCED                32840
#define ID_LIST_CONFIGURECACHING        32841
#define ID_LIST_EDITHIGHLIGHTKEYWORDS   32842
#define ID_LIST_GROUPFAVORITESATTOPOFLIST 32843
#define ID_LIST_HIGHLIGHT               32844
#define ID_LIST_LOCKFOCUSONSELECTION    32845
#define ID_LIST_RELOADLIST              32846
#define ID_LIST_REMOVEFROMFAVORITES     32847
#define ID_LIST_UPDATELIST              32848
#define ID_METIS_EDIT_FILELIST          32849
#define ID_METIS_RELOADCONFIGURATION    32850
#define ID_METIS_START                  32851
#define ID_METIS_STOP                   32852
#define ID_MUTE                         32853
#define ID_MYFILE_NEW                   32854
#define ID_NEXT                         32855
#define ID_OK                           32856
#define ID_OPEN_OPEN                    32857
#define ID_OPEN_OPENINNEWBROWSER        32858
#define ID_POPUP_ADVANCED               32859
#define ID_POPUP_COPYROOMNAME           32860
#define ID_POPUP_COPYTOPIC              32861
#define ID_POPUP_DELETE                 32862
#define ID_POPUP_LOOPBACKJOIN           32863
#define ID_POPUP_PINGROOM               32864
#define ID_PREV                         32865
#define ID_PRIVATEMESSAGE_SETAUTORESPONDER 32866
#define ID_RECONNECT                    32867
#define ID_RECONNECT_ALL                32868
#define ID_RENAME                       32869
#define ID_ROBOMX_CONNECTNEWCHANNEL     32870
#define ID_ROBOMX_OPENSERVERCONFIGURATION 32871
#define ID_ROBOMX_SAVESERVERCONFIGURATION 32872
#define ID_SEND_FAILED                  32873
#define ID_SYSTRAY_RESTORE              32874
#define ID_TEXTTRICKS_3DBUTTONS         32875
#define ID_USER_BROWSE                  32876
#define ID_USERLIST_ADDADMIN            32877
#define ID_USERLIST_BAN                 32878
#define ID_USERLIST_COPYUSERNAME        32879
#define ID_USERLIST_CUSTOMCOMMANDS      32880
#define ID_USERLIST_CUSTOMIZETHISMENU   32881
#define ID_USERLIST_IGNORE              32882
#define ID_USERLIST_KICK                32883
#define ID_USERLIST_KICKBAN             32884
#define ID_USERLIST_PRINTIP             32885
#define ID_USERLIST_PRINTUSERSTAT       32886
#define ID_USERLIST_READUSERMESSAGE     32887
#define ID_USERLIST_REDIRECT            32888
#define ID_USERLIST_REMOVEADMIN         32889
#define ID_USERLIST_SENDMESSAGE         32890
#define ID_USERLIST_UNBAN               32891
#define ID_USERLIST_UNIGNORE            32892
#define ID_USERLIST_WHOIS               32893
#define ID_VIEW_AUTOJOINMANAGER         32894
#define ID_VIEW_CHANNELBAR              32895
#define ID_VIEW_FULL_SCREEN             32896
#define ID_VIEW_IGNOREDUSERS            32897
#define ID_VIEW_LOGFILE                 32898
#define ID_VIEW_MENUBAR                 32899
#define ID_VIEW_OPTIONS                 32900
#define ID_VIEW_SYSTEMCONSOLE           32901
#define ID_VIEW_TRUSTEDUSERS            32902
#define ID_WPN_REFRESH                  32903
#define ID_WPN_STATUS                   32904
#define ID_LIST_CACHEONLYFAVORITES      32905
#define ID_ACTIONS_TRUSTUSER            32906
#define ID_DISPLAYINCHANNEL_STATISTICS  32907
#define ID_TEXTTRICKS_WILDCOLORS        32911
#define ID_VIEW_SYSTEM_BAR              32913
#define ID_VIEW_USERLIST_BAR            32915
#define ID_DISPLAYINCHANNEL_EXTENDEDSYSTEMINFO 32917
#define ID_SHIFTENTER                   32919
#define ID_CTRLTAB                      32921
#define ID_POPUP_EDITFAVORITEENTRY      32923
#define ID_USERLIST_ADVANCED            32924
#define ID_ADVANCED_TRUSTUSER           32925
#define ID_ADVANCED_REMOVETRUSTED       32926
#define ID_LIST_SHOWSTATISTICS          32927
#define ID_LIST_COPYSTATISTICS          32928
#define ID_CTRLSHIFTTAB                 32930
#define ID_DISPLAYINCHANNEL_ONLINETIME  32932
#define ID_HELP_VISITONLINEFORUM        32936
#define ID_HELP_SUBSCRIBETOMAILINGLIST  32937
#define ID_CHANNELLIST_ADVANCED         32938
#define ID_HELP_LINCENSE                32939
#define ID_HELP_CHANGELOG               32940
#define ID_USERLIST_ADVANCED32941       32941
#define ID_Menu                         32942
#define ID_Menu32943                    32943
#define ID_DOCMENU_SETCHANNELPICTURE    32944
#define ID_ADVANCED_SETPICTURE          32945
#define ID_VIEW_USERLIST                32946
#define ID_USERLIST_DETAILEDVIEW        32947
#define ID_USERLIST_SHORTVIEW           32948
#define ID_USERLIST_BIGICONS            32949
#define ID_USERLIST_SMALLICONS          32950
#define ID_DELETE_CHANNEL               32951
#define IDS_SYSTEMUPTIME                61204
#define IDC_WPNNAME                     61205
#define IDS_MCMARAWNAMEWARNING          61206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        406
#define _APS_NEXT_COMMAND_VALUE         32953
#define _APS_NEXT_CONTROL_VALUE         1393
#define _APS_NEXT_SYMED_VALUE           1415
#endif
#endif
